### ISSUE TITLE
What's up with all the deleted code?

### ISSUE THREAD

**Issue by dstndstn** [ameisner/WISE#1]
Hi Aaron,

I have been using your great PSF models for generative models of the WISE data.  I see you removed a bunch of code from this repo in early December, including wise_psf_cutout.pro -- what's up?  I don't see any modified or added code, so I don't think you moved it to another file.  If you're not using it for your own work, could I convince you to leave it in the repo for others?

Thanks,
--dustin

**Comment by ameisner** [comment]
Hi Dustin,

Wow, how did I not see this issue until now?? Definitely my bad. At some point I felt weirded out about posting code that Doug had written or contributed to online without having sought his consent, and apparently I just started deleting a bunch of stuff. My bad there also. Even sillier given the way that git file "deletion" works.

I've now restored enough code so that PSF model generation works again. As you say, nothing was modified throughout this process, so the PSF models are unchanged. Thanks.

-Aaron
